#!/usr/bin/env python3
"""
Analyze benchmark results for growth-sweep experiments.

Inputs:
  - consolidated benchmark JSON (e.g., full_results.json)
  - growth manifest JSON (e.g., growth_manifest.json)

Outputs:
  - grouped summary JSON with per-solver, per-axis, per-level stats
"""

from __future__ import annotations

import argparse
import json
import statistics
from collections import defaultdict
from typing import Dict, List, Tuple


def load_json(path: str):
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Analyze temporal growth sweep benchmark outputs")
    p.add_argument("results_json", help="Consolidated benchmark JSON containing a 'results' array")
    p.add_argument("manifest_json", help="Manifest generated by generate_growth_sweeps.py")
    p.add_argument("-o", "--output", default="growth_summary.json", help="Output summary JSON")
    return p.parse_args()


def summarize_bucket(rows: List[dict]) -> Dict[str, float | int | None]:
    total = len(rows)
    success = [r for r in rows if r.get("status") == "success" and isinstance(r.get("time"), (int, float))]
    timeout = [r for r in rows if r.get("status") == "timeout"]
    failed = [r for r in rows if r.get("status") == "failed"]

    out: Dict[str, float | int | None] = {
        "n": total,
        "success": len(success),
        "timeout": len(timeout),
        "failed": len(failed),
        "success_rate": (100.0 * len(success) / total) if total else 0.0,
        "timeout_rate": (100.0 * len(timeout) / total) if total else 0.0,
        "mean_time": None,
        "median_time": None,
        "p90_time": None,
    }

    if success:
        times = sorted(float(r["time"]) for r in success)
        out["mean_time"] = statistics.mean(times)
        out["median_time"] = statistics.median(times)
        k = int(round(0.9 * (len(times) - 1)))
        out["p90_time"] = times[k]

    return out


def main() -> None:
    args = parse_args()

    raw_results = load_json(args.results_json)
    manifest = load_json(args.manifest_json)

    results = raw_results["results"] if isinstance(raw_results, dict) and "results" in raw_results else raw_results

    instance_map = {inst["game"]: inst for inst in manifest.get("instances", [])}

    # solver -> axis -> level -> rows
    grouped: Dict[str, Dict[str, Dict[str, List[dict]]]] = defaultdict(lambda: defaultdict(lambda: defaultdict(list)))

    unmatched_games = 0
    for row in results:
        game = row.get("game")
        solver = str(row.get("solver", "unknown"))
        if game not in instance_map:
            unmatched_games += 1
            continue

        inst = instance_map[game]
        axis = inst["axis"]
        level = str(inst["level"])
        grouped[solver][axis][level].append(row)

    summary = {
        "experiment": manifest.get("experiment", "unknown"),
        "results_file": args.results_json,
        "manifest_file": args.manifest_json,
        "unmatched_result_rows": unmatched_games,
        "solvers": {},
    }

    for solver, by_axis in grouped.items():
        solver_out = {}
        for axis, by_level in by_axis.items():
            axis_out = {}
            for level, rows in sorted(by_level.items(), key=lambda kv: kv[0]):
                axis_out[level] = summarize_bucket(rows)
            solver_out[axis] = axis_out
        summary["solvers"][solver] = solver_out

    with open(args.output, "w", encoding="utf-8") as f:
        json.dump(summary, f, indent=2)

    # concise terminal summary
    print("Growth sweep analysis completed")
    print(f"  output: {args.output}")
    print(f"  unmatched rows: {unmatched_games}")
    print("")

    for solver, by_axis in summary["solvers"].items():
        print(f"Solver: {solver}")
        for axis, by_level in by_axis.items():
            print(f"  Axis: {axis}")
            for level, stats in by_level.items():
                m = stats["mean_time"]
                m_str = f"{m:.6f}s" if isinstance(m, (int, float)) else "n/a"
                print(
                    f"    level={level:>10} | n={stats['n']:3d} | success={stats['success_rate']:5.1f}%"
                    f" | timeout={stats['timeout_rate']:5.1f}% | mean={m_str}"
                )
        print("")


if __name__ == "__main__":
    main()
